/**
 * Países em português, código ISO-3166-1 alpha-2.
 *
 * Gerado a partir de `Intl.DisplayNames(['pt-BR'], { type: 'region' })` e
 * gravado como constante em vez de resolvido em tempo de execução: o Hermes,
 * motor JS do React Native, não garante `Intl.DisplayNames` em todo aparelho
 * Android. Uma lista de países vazia no celular de alguém é pior do que uma
 * constante de 257 linhas no bundle.
 *
 * Agrupamentos (UE, ONU), zonas reservadas e códigos extintos ficaram de fora.
 */
export type Pais = { codigo: string; nome: string };

export const PAISES: readonly Pais[] = [
  { codigo: 'AF', nome: 'Afeganistão' },
  { codigo: 'ZA', nome: 'África do Sul' },
  { codigo: 'AL', nome: 'Albânia' },
  { codigo: 'DE', nome: 'Alemanha' },
  { codigo: 'AD', nome: 'Andorra' },
  { codigo: 'AO', nome: 'Angola' },
  { codigo: 'AI', nome: 'Anguila' },
  { codigo: 'AQ', nome: 'Antártida' },
  { codigo: 'AG', nome: 'Antígua e Barbuda' },
  { codigo: 'SA', nome: 'Arábia Saudita' },
  { codigo: 'DZ', nome: 'Argélia' },
  { codigo: 'AR', nome: 'Argentina' },
  { codigo: 'AM', nome: 'Armênia' },
  { codigo: 'AW', nome: 'Aruba' },
  { codigo: 'AU', nome: 'Austrália' },
  { codigo: 'AT', nome: 'Áustria' },
  { codigo: 'AZ', nome: 'Azerbaijão' },
  { codigo: 'BS', nome: 'Bahamas' },
  { codigo: 'BD', nome: 'Bangladesh' },
  { codigo: 'BB', nome: 'Barbados' },
  { codigo: 'BH', nome: 'Barein' },
  { codigo: 'BE', nome: 'Bélgica' },
  { codigo: 'BZ', nome: 'Belize' },
  { codigo: 'BJ', nome: 'Benin' },
  { codigo: 'DY', nome: 'Benin' },
  { codigo: 'BM', nome: 'Bermudas' },
  { codigo: 'BY', nome: 'Bielorrússia' },
  { codigo: 'BO', nome: 'Bolívia' },
  { codigo: 'BA', nome: 'Bósnia e Herzegovina' },
  { codigo: 'BW', nome: 'Botsuana' },
  { codigo: 'BR', nome: 'Brasil' },
  { codigo: 'BN', nome: 'Brunei' },
  { codigo: 'BG', nome: 'Bulgária' },
  { codigo: 'BF', nome: 'Burquina Faso' },
  { codigo: 'HV', nome: 'Burquina Faso' },
  { codigo: 'BI', nome: 'Burundi' },
  { codigo: 'BT', nome: 'Butão' },
  { codigo: 'CV', nome: 'Cabo Verde' },
  { codigo: 'CM', nome: 'Camarões' },
  { codigo: 'KH', nome: 'Camboja' },
  { codigo: 'CA', nome: 'Canadá' },
  { codigo: 'QA', nome: 'Catar' },
  { codigo: 'KZ', nome: 'Cazaquistão' },
  { codigo: 'TD', nome: 'Chade' },
  { codigo: 'CL', nome: 'Chile' },
  { codigo: 'CN', nome: 'China' },
  { codigo: 'CY', nome: 'Chipre' },
  { codigo: 'VA', nome: 'Cidade do Vaticano' },
  { codigo: 'CO', nome: 'Colômbia' },
  { codigo: 'KM', nome: 'Comores' },
  { codigo: 'CD', nome: 'Congo - Kinshasa' },
  { codigo: 'KP', nome: 'Coreia do Norte' },
  { codigo: 'KR', nome: 'Coreia do Sul' },
  { codigo: 'CI', nome: 'Costa do Marfim' },
  { codigo: 'CR', nome: 'Costa Rica' },
  { codigo: 'HR', nome: 'Croácia' },
  { codigo: 'CU', nome: 'Cuba' },
  { codigo: 'CW', nome: 'Curaçao' },
  { codigo: 'DK', nome: 'Dinamarca' },
  { codigo: 'DJ', nome: 'Djibuti' },
  { codigo: 'DM', nome: 'Dominica' },
  { codigo: 'EG', nome: 'Egito' },
  { codigo: 'SV', nome: 'El Salvador' },
  { codigo: 'AE', nome: 'Emirados Árabes Unidos' },
  { codigo: 'EC', nome: 'Equador' },
  { codigo: 'ER', nome: 'Eritreia' },
  { codigo: 'SK', nome: 'Eslováquia' },
  { codigo: 'SI', nome: 'Eslovênia' },
  { codigo: 'ES', nome: 'Espanha' },
  { codigo: 'SZ', nome: 'Essuatíni' },
  { codigo: 'US', nome: 'Estados Unidos' },
  { codigo: 'EE', nome: 'Estônia' },
  { codigo: 'ET', nome: 'Etiópia' },
  { codigo: 'FJ', nome: 'Fiji' },
  { codigo: 'PH', nome: 'Filipinas' },
  { codigo: 'FI', nome: 'Finlândia' },
  { codigo: 'FR', nome: 'França' },
  { codigo: 'GA', nome: 'Gabão' },
  { codigo: 'GM', nome: 'Gâmbia' },
  { codigo: 'GH', nome: 'Gana' },
  { codigo: 'GE', nome: 'Geórgia' },
  { codigo: 'GI', nome: 'Gibraltar' },
  { codigo: 'GD', nome: 'Granada' },
  { codigo: 'GR', nome: 'Grécia' },
  { codigo: 'GL', nome: 'Groenlândia' },
  { codigo: 'GP', nome: 'Guadalupe' },
  { codigo: 'GU', nome: 'Guam' },
  { codigo: 'GT', nome: 'Guatemala' },
  { codigo: 'GG', nome: 'Guernsey' },
  { codigo: 'GY', nome: 'Guiana' },
  { codigo: 'GF', nome: 'Guiana Francesa' },
  { codigo: 'GN', nome: 'Guiné' },
  { codigo: 'GQ', nome: 'Guiné Equatorial' },
  { codigo: 'GW', nome: 'Guiné-Bissau' },
  { codigo: 'HT', nome: 'Haiti' },
  { codigo: 'HN', nome: 'Honduras' },
  { codigo: 'HK', nome: 'Hong Kong, RAE da China' },
  { codigo: 'HU', nome: 'Hungria' },
  { codigo: 'YD', nome: 'Iêmen' },
  { codigo: 'YE', nome: 'Iêmen' },
  { codigo: 'BV', nome: 'Ilha Bouvet' },
  { codigo: 'CX', nome: 'Ilha Christmas' },
  { codigo: 'IM', nome: 'Ilha de Man' },
  { codigo: 'NF', nome: 'Ilha Norfolk' },
  { codigo: 'AX', nome: 'Ilhas Aland' },
  { codigo: 'KY', nome: 'Ilhas Cayman' },
  { codigo: 'CC', nome: 'Ilhas Cocos (Keeling)' },
  { codigo: 'CK', nome: 'Ilhas Cook' },
  { codigo: 'FO', nome: 'Ilhas Faroé' },
  { codigo: 'GS', nome: 'Ilhas Geórgia do Sul e Sandwich do Sul' },
  { codigo: 'HM', nome: 'Ilhas Heard e McDonald' },
  { codigo: 'FK', nome: 'Ilhas Malvinas' },
  { codigo: 'MP', nome: 'Ilhas Marianas do Norte' },
  { codigo: 'MH', nome: 'Ilhas Marshall' },
  { codigo: 'UM', nome: 'Ilhas Menores Distantes dos EUA' },
  { codigo: 'PN', nome: 'Ilhas Pitcairn' },
  { codigo: 'SB', nome: 'Ilhas Salomão' },
  { codigo: 'TC', nome: 'Ilhas Turcas e Caicos' },
  { codigo: 'VI', nome: 'Ilhas Virgens Americanas' },
  { codigo: 'VG', nome: 'Ilhas Virgens Britânicas' },
  { codigo: 'IN', nome: 'Índia' },
  { codigo: 'ID', nome: 'Indonésia' },
  { codigo: 'IR', nome: 'Irã' },
  { codigo: 'IQ', nome: 'Iraque' },
  { codigo: 'IE', nome: 'Irlanda' },
  { codigo: 'IS', nome: 'Islândia' },
  { codigo: 'IL', nome: 'Israel' },
  { codigo: 'IT', nome: 'Itália' },
  { codigo: 'JM', nome: 'Jamaica' },
  { codigo: 'JP', nome: 'Japão' },
  { codigo: 'JE', nome: 'Jersey' },
  { codigo: 'JO', nome: 'Jordânia' },
  { codigo: 'XK', nome: 'Kosovo' },
  { codigo: 'KW', nome: 'Kuwait' },
  { codigo: 'LA', nome: 'Laos' },
  { codigo: 'LS', nome: 'Lesoto' },
  { codigo: 'LV', nome: 'Letônia' },
  { codigo: 'LB', nome: 'Líbano' },
  { codigo: 'LR', nome: 'Libéria' },
  { codigo: 'LY', nome: 'Líbia' },
  { codigo: 'LI', nome: 'Liechtenstein' },
  { codigo: 'LT', nome: 'Lituânia' },
  { codigo: 'LU', nome: 'Luxemburgo' },
  { codigo: 'MO', nome: 'Macau, RAE da China' },
  { codigo: 'MK', nome: 'Macedônia do Norte' },
  { codigo: 'MG', nome: 'Madagascar' },
  { codigo: 'MY', nome: 'Malásia' },
  { codigo: 'MW', nome: 'Malaui' },
  { codigo: 'MV', nome: 'Maldivas' },
  { codigo: 'ML', nome: 'Mali' },
  { codigo: 'MT', nome: 'Malta' },
  { codigo: 'MA', nome: 'Marrocos' },
  { codigo: 'MQ', nome: 'Martinica' },
  { codigo: 'MU', nome: 'Maurício' },
  { codigo: 'MR', nome: 'Mauritânia' },
  { codigo: 'YT', nome: 'Mayotte' },
  { codigo: 'MX', nome: 'México' },
  { codigo: 'MM', nome: 'Mianmar (Birmânia)' },
  { codigo: 'FM', nome: 'Micronésia' },
  { codigo: 'MZ', nome: 'Moçambique' },
  { codigo: 'MD', nome: 'Moldávia' },
  { codigo: 'MC', nome: 'Mônaco' },
  { codigo: 'MN', nome: 'Mongólia' },
  { codigo: 'ME', nome: 'Montenegro' },
  { codigo: 'MS', nome: 'Montserrat' },
  { codigo: 'NA', nome: 'Namíbia' },
  { codigo: 'NR', nome: 'Nauru' },
  { codigo: 'NP', nome: 'Nepal' },
  { codigo: 'NI', nome: 'Nicarágua' },
  { codigo: 'NE', nome: 'Níger' },
  { codigo: 'NG', nome: 'Nigéria' },
  { codigo: 'NU', nome: 'Niue' },
  { codigo: 'NO', nome: 'Noruega' },
  { codigo: 'NC', nome: 'Nova Caledônia' },
  { codigo: 'NZ', nome: 'Nova Zelândia' },
  { codigo: 'OM', nome: 'Omã' },
  { codigo: 'NL', nome: 'Países Baixos' },
  { codigo: 'BQ', nome: 'Países Baixos Caribenhos' },
  { codigo: 'PW', nome: 'Palau' },
  { codigo: 'PA', nome: 'Panamá' },
  { codigo: 'PG', nome: 'Papua-Nova Guiné' },
  { codigo: 'PK', nome: 'Paquistão' },
  { codigo: 'PY', nome: 'Paraguai' },
  { codigo: 'PE', nome: 'Peru' },
  { codigo: 'PF', nome: 'Polinésia Francesa' },
  { codigo: 'PL', nome: 'Polônia' },
  { codigo: 'PR', nome: 'Porto Rico' },
  { codigo: 'PT', nome: 'Portugal' },
  { codigo: 'KE', nome: 'Quênia' },
  { codigo: 'KG', nome: 'Quirguistão' },
  { codigo: 'KI', nome: 'Quiribati' },
  { codigo: 'GB', nome: 'Reino Unido' },
  { codigo: 'UK', nome: 'Reino Unido' },
  { codigo: 'CF', nome: 'República Centro-Africana' },
  { codigo: 'CG', nome: 'República do Congo' },
  { codigo: 'DO', nome: 'República Dominicana' },
  { codigo: 'RE', nome: 'Reunião' },
  { codigo: 'RO', nome: 'Romênia' },
  { codigo: 'RW', nome: 'Ruanda' },
  { codigo: 'RU', nome: 'Rússia' },
  { codigo: 'EH', nome: 'Saara Ocidental' },
  { codigo: 'WS', nome: 'Samoa' },
  { codigo: 'AS', nome: 'Samoa Americana' },
  { codigo: 'SM', nome: 'San Marino' },
  { codigo: 'SH', nome: 'Santa Helena' },
  { codigo: 'LC', nome: 'Santa Lúcia' },
  { codigo: 'BL', nome: 'São Bartolomeu' },
  { codigo: 'KN', nome: 'São Cristóvão e Névis' },
  { codigo: 'MF', nome: 'São Martinho' },
  { codigo: 'PM', nome: 'São Pedro e Miquelão' },
  { codigo: 'ST', nome: 'São Tomé e Príncipe' },
  { codigo: 'VC', nome: 'São Vicente e Granadinas' },
  { codigo: 'SC', nome: 'Seicheles' },
  { codigo: 'SN', nome: 'Senegal' },
  { codigo: 'SL', nome: 'Serra Leoa' },
  { codigo: 'RS', nome: 'Sérvia' },
  { codigo: 'SG', nome: 'Singapura' },
  { codigo: 'SX', nome: 'Sint Maarten' },
  { codigo: 'SY', nome: 'Síria' },
  { codigo: 'SO', nome: 'Somália' },
  { codigo: 'LK', nome: 'Sri Lanka' },
  { codigo: 'SD', nome: 'Sudão' },
  { codigo: 'SS', nome: 'Sudão do Sul' },
  { codigo: 'SE', nome: 'Suécia' },
  { codigo: 'CH', nome: 'Suíça' },
  { codigo: 'SR', nome: 'Suriname' },
  { codigo: 'SJ', nome: 'Svalbard e Jan Mayen' },
  { codigo: 'TJ', nome: 'Tadjiquistão' },
  { codigo: 'TH', nome: 'Tailândia' },
  { codigo: 'TW', nome: 'Taiwan' },
  { codigo: 'TZ', nome: 'Tanzânia' },
  { codigo: 'CZ', nome: 'Tchéquia' },
  { codigo: 'IO', nome: 'Território Britânico do Oceano Índico' },
  { codigo: 'TF', nome: 'Territórios Franceses do Sul' },
  { codigo: 'PS', nome: 'Territórios palestinos' },
  { codigo: 'TL', nome: 'Timor-Leste' },
  { codigo: 'TG', nome: 'Togo' },
  { codigo: 'TK', nome: 'Tokelau' },
  { codigo: 'TO', nome: 'Tonga' },
  { codigo: 'TT', nome: 'Trinidad e Tobago' },
  { codigo: 'TN', nome: 'Tunísia' },
  { codigo: 'TM', nome: 'Turcomenistão' },
  { codigo: 'TR', nome: 'Turquia' },
  { codigo: 'TV', nome: 'Tuvalu' },
  { codigo: 'UA', nome: 'Ucrânia' },
  { codigo: 'UG', nome: 'Uganda' },
  { codigo: 'UY', nome: 'Uruguai' },
  { codigo: 'UZ', nome: 'Uzbequistão' },
  { codigo: 'NH', nome: 'Vanuatu' },
  { codigo: 'VU', nome: 'Vanuatu' },
  { codigo: 'VE', nome: 'Venezuela' },
  { codigo: 'VD', nome: 'Vietnã' },
  { codigo: 'VN', nome: 'Vietnã' },
  { codigo: 'WF', nome: 'Wallis e Futuna' },
  { codigo: 'ZM', nome: 'Zâmbia' },
  { codigo: 'RH', nome: 'Zimbábue' },
  { codigo: 'ZW', nome: 'Zimbábue' },
] as const;

/** Nome do país a partir do código. Devolve o próprio código se não conhecer. */
export function nomeDoPais(codigo: string | null | undefined): string {
  if (!codigo) return '';
  const achado = PAISES.find((p) => p.codigo === codigo.toUpperCase());
  return achado?.nome ?? codigo.toUpperCase();
}
